### PR TITLE
Chapter 28

### PR DESCRIPTION
**Pull request by aryan-kancherla**

### CODE REVIEW

**Comment by davidkane9** [comment]
Can you fix the error?

**Comment by davidkane9** [comment]
Doing pr_merge_main() and accepting my version of the renv files should do it.

**Comment by aryan-kancherla** [comment]
I ran pr_merge_main() but the error still shows up. I also updated Rstudio
& the renv library but those didn't seem to work either.

**Comment by davidkane9** [comment]
Problem is your PR includes bad changes to renv/activate.R. Submit a new PR which only changes tutorial.Rmd. You may need to nuke from orbit, as described in my docs.

**Pull request closed without merging**
