### PR TITLE
Fixed mistakes in Tutorial 1.

### PR DESCRIPTION
**Pull request by MPCode2020**

### CODE REVIEW

**Comment by MPCode2020** [comment]
It seems like the R-CMD-check checks are failing due to an example code chunk I used: 

```{r}
data |> 
  ggplot(mapping = aes(x = foo))
```

Please advise @davidkane9, TIA!

**Comment by davidkane9** [comment]
Example code chunks must work. No nonsense like foo

**Comment by MPCode2020** [comment]
Fixed -- removed chunk and replaced it with inline code (which if I'm not mistaken doesn't run in R-CMD-check). Thanks!

**Comment by davidkane9** [comment]
This is excellent! I will accept it when we chat next so we can discuss things. Go one to chapter 2.

**Pull request merged**
