### PR TITLE
work

### PR DESCRIPTION
**Pull request by sharav12**

### CODE REVIEW

**Comment by davidkane9** [comment]
There seem to be some strange typos --- words like "work" and "main" in random places. Can you take a look? Maybe they belong and I just don't see it . . .

**Comment by sharav12** [comment]
I'm not sure what you mean, as i've looked and don't see anything out of the ordinary

**Comment by davidkane9** [comment]
Any updates?

**Comment by sharav12** [comment]
Hello preceptor.
It’s been a while. I’ve settled into the routine of school and can
confidently say that I can contribute 6-8 hours a week to your work. I’m
very interested in continuing this. Looking forward to hearing from you.
Thanks
Sharav

LANDSLOT

**Pull request closed without merging**
