### PR TITLE
chapter 24 first section done

### PR DESCRIPTION
**Pull request by SplashyZues5197**

### CODE REVIEW

**Comment by SplashyZues5197** [comment]
Quick question: why is chapter 24 not in the schedule?

**Comment by SplashyZues5197** [comment]
the tutorial is working when I run it, I think it's because of the library version of the tutorials.

**Comment by davidkane9** [comment]
Can you shrink the size of these images? 250k is too big. See the examples in the joins chapter.

**Comment by davidkane9** [comment]
repurrrsive package was needed. that is fixed. But please fix the image size.

**Comment by SplashyZues5197** [comment]
made it smaller to 60 to 80 range

**Pull request merged**
